//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperLigForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antrenor
    {
        public byte antrenorID { get; set; }
        public string Adi { get; set; }
        public Nullable<int> TakimID { get; set; }
        public string Ulke { get; set; }
        public Nullable<int> Yas { get; set; }
        public Nullable<int> CalistidigiTakimSayisi { get; set; }
        public string CalistiridigiTakim { get; set; }
    }
}
