//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperLigForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maclar
    {
        public int MacID { get; set; }
        public Nullable<byte> EvSahibiTakim { get; set; }
        public Nullable<byte> RakipTakim { get; set; }
        public Nullable<byte> EAttigiGol { get; set; }
        public Nullable<byte> RAttigiGol { get; set; }
        public Nullable<byte> Hafta { get; set; }
    }
}
