//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperLigForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takim
    {
        public byte TakimID { get; set; }
        public string TakimAdi { get; set; }
        public Nullable<byte> OynadigiMac { get; set; }
        public Nullable<byte> Galibiyet { get; set; }
        public Nullable<byte> Maglubiyet { get; set; }
        public Nullable<byte> Beraberlik { get; set; }
        public Nullable<int> Averaj { get; set; }
        public Nullable<int> AttigiGol { get; set; }
        public Nullable<int> YedigiGol { get; set; }
        public Nullable<int> PuanDurumu { get; set; }
    }
}
