//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperLigForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OlasiMaclar
    {
        public byte evsahibid { get; set; }
        public string evsahibiadi { get; set; }
        public byte konukid { get; set; }
        public string konukadi { get; set; }
        public Nullable<int> mackodu { get; set; }
    }
}
